/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./app/**/*.{js,jsx}",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1440px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border-subtle))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        /* Glass & Slate extended palette */
        "gs-canvas": "hsl(var(--canvas))",
        "gs-surface": "hsl(var(--surface))",
        "gs-elevated": "hsl(var(--elevated))",
        "gs-border": "hsl(var(--border))",
        "gs-border-subtle": "hsl(var(--border-subtle))",
        "gs-text-primary": "hsl(var(--text-primary))",
        "gs-text-secondary": "hsl(var(--text-secondary))",
        "gs-text-muted": "hsl(var(--text-muted))",
        "gs-accent": "hsl(var(--accent-primary))",
        "gs-accent-container": "hsl(var(--accent-primary-container))",
        "gs-success": "hsl(var(--accent-secondary))",
        "gs-success-container": "hsl(var(--accent-secondary-container))",
        "gs-warn": "hsl(var(--accent-tertiary))",
        "gs-error": "hsl(var(--error))",

        /* Mockup Tokens */
        "on-secondary-fixed-variant": "#005236",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#723600",
        "on-secondary-fixed": "#002113",
        "inverse-surface": "#e1e2ec",
        "tertiary-container": "#df7412",
        "surface-container-high": "#272a31",
        "inverse-primary": "#005ac2",
        "error": "#ffb4ab",
        "primary-fixed": "#d8e2ff",
        "on-secondary": "#003824",
        "primary-container": "#4d8eff",
        "on-primary": "#002e6a",
        "on-error": "#690005",
        "on-background": "#e1e2ec",
        "on-tertiary-container": "#461f00",
        "tertiary-fixed-dim": "#ffb786",
        "tertiary-fixed": "#ffdcc6",
        "tertiary": "#ffb786",
        "outline": "#8c909f",
        "error-container": "#93000a",
        "surface-dim": "#10131a",
        "surface": "#10131a",
        "on-primary-container": "#00285d",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary": "#502400",
        "secondary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#adc6ff",
        "secondary-fixed-dim": "#4edea3",
        "inverse-on-surface": "#2e3038",
        "background": "#10131a",
        "surface-bright": "#363941",
        "surface-container": "#1d2027",
        "on-surface": "#e1e2ec",
        "on-tertiary-fixed": "#311400",
        "on-primary-fixed": "#001a42",
        "surface-variant": "#32353c",
        "surface-tint": "#adc6ff",
        "surface-container-highest": "#32353c",
        "on-surface-variant": "#c2c6d6",
        "surface-container-lowest": "#0b0e15",
        "surface-container-low": "#191b23",
        "secondary-container": "#00a572",
        "outline-variant": "#424754",
        "on-secondary-container": "#00311f"
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'Courier New', 'monospace'],
        metadata: ['JetBrains Mono', 'monospace'],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "metadata": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "body-lg": ["16px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
      },
      spacing: {
        'gutter': '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'container-max': '1440px',
        'unit': '4px'
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(-4px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-in-left": {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(0)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "0.8" },
        },
        "shimmer": {
          from: { backgroundPosition: "-200% 0" },
          to: { backgroundPosition: "200% 0" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "slide-in-right": "slide-in-right 0.3s ease-out",
        "slide-in-left": "slide-in-left 0.3s ease-out",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "shimmer": "shimmer 2s linear infinite",
        "spin-slow": "spin-slow 3s linear infinite",
      },
      backdropBlur: {
        xs: "2px",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};