/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("model_catalog");
  if (!collection) {
    console.log("model_catalog collection not found, skipping seed");
    return;
  }

  const models = [
    {
      key: "grok-3",
      label: "Grok 3",
      provider: "xAI",
      type: "video",
      billing: "per_video",
      credits: { "480p": 25, "720p": 25 },
      creditsPerSecond: null,
      durations: [6, 10, 15],
      minDuration: null,
      maxDuration: 15,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: true,
      enabled: true,
      sortOrder: 10,
      vendorModelId: "grok-3",
      description: "xAI Grok 3 video generation",
      category: "Standard"
    },
    {
      key: "veo-3.1-fast",
      label: "Veo 3.1 Fast",
      provider: "Google",
      type: "video",
      billing: "per_video",
      credits: { "720p": 15, "1080p": 15 },
      creditsPerSecond: null,
      durations: [8],
      minDuration: null,
      maxDuration: 8,
      aspectRatios: ["16:9", "9:16"],
      imageModes: ["frame", "ingredient"],
      maxRefImages: 3,
      freeAccess: false,
      routed: true,
      enabled: true,
      sortOrder: 20,
      vendorModelId: "veo-3.1-fast",
      description: "Fast Veo 3.1 generation",
      category: "Fast"
    },
    {
      key: "veo-3.1-lite",
      label: "Veo 3.1 Lite",
      provider: "Google",
      type: "video",
      billing: "per_video",
      credits: { "720p": 15, "1080p": 15 },
      creditsPerSecond: null,
      durations: [8],
      minDuration: null,
      maxDuration: 8,
      aspectRatios: ["16:9", "9:16"],
      imageModes: ["frame", "ingredient"],
      maxRefImages: 3,
      freeAccess: true,
      routed: true,
      enabled: true,
      sortOrder: 5,
      vendorModelId: "veo-3.1-lite",
      description: "Free-tier Veo 3.1 model",
      category: "Free"
    },
    {
      key: "veo-3.1",
      label: "Veo 3.1",
      provider: "Google",
      type: "video",
      billing: "per_video",
      credits: { "720p": 500, "1080p": 500 },
      creditsPerSecond: null,
      durations: [8],
      minDuration: null,
      maxDuration: 8,
      aspectRatios: ["16:9", "9:16"],
      imageModes: ["frame", "ingredient"],
      maxRefImages: 3,
      freeAccess: false,
      routed: true,
      enabled: true,
      sortOrder: 30,
      vendorModelId: "veo-3.1",
      description: "Premium Veo 3.1 quality",
      category: "Premium"
    },
    {
      key: "kling-2.5-relax",
      label: "Kling 2.5 Relax",
      provider: "Kling",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 15 },
      durations: [5, 10],
      minDuration: null,
      maxDuration: null,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 100,
      vendorModelId: "kling-2.5-relax",
      description: "Kling 2.5 relaxed mode",
      category: "Standard"
    },
    {
      key: "kling-2.5",
      label: "Kling 2.5",
      provider: "Kling",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 30, "1080p": 40 },
      durations: [5, 10],
      minDuration: null,
      maxDuration: null,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 101,
      vendorModelId: "kling-2.5",
      description: "Kling 2.5 standard quality",
      category: "Standard"
    },
    {
      key: "kling-2.6",
      label: "Kling 2.6",
      provider: "Kling",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 30, "1080p": 50 },
      durations: [5, 10],
      minDuration: null,
      maxDuration: null,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 102,
      vendorModelId: "kling-2.6",
      description: "Kling 2.6 with audio support",
      category: "Standard"
    },
    {
      key: "kling-2.6-audio",
      label: "Kling 2.6 Audio",
      provider: "Kling",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "1080p": 70 },
      durations: [5, 10],
      minDuration: null,
      maxDuration: null,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 103,
      vendorModelId: "kling-2.6-audio",
      description: "Kling 2.6 with audio generation",
      category: "Premium"
    },
    {
      key: "kling-2.1-10s",
      label: "Kling 2.1 (10s)",
      provider: "Kling",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 30, "1080p": 60 },
      durations: [10],
      minDuration: null,
      maxDuration: null,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 110,
      vendorModelId: "kling-2.1",
      description: "Kling 2.1 - 10 second clips",
      category: "Standard"
    },
    {
      key: "kling-2.1-5s",
      label: "Kling 2.1 (5s)",
      provider: "Kling",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 35, "1080p": 60 },
      durations: [5],
      minDuration: null,
      maxDuration: null,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 111,
      vendorModelId: "kling-2.1",
      description: "Kling 2.1 - 5 second clips",
      category: "Standard"
    },
    {
      key: "kling-3.0",
      label: "Kling 3.0",
      provider: "Kling",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 50, "1080p": 60 },
      durations: null,
      minDuration: 3,
      maxDuration: 15,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 104,
      vendorModelId: "kling-3.0",
      description: "Kling 3.0 latest generation",
      category: "Premium"
    },
    {
      key: "kling-3.0-edit",
      label: "Kling 3.0 Edit",
      provider: "Kling",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 60, "1080p": 75 },
      durations: null,
      minDuration: 3,
      maxDuration: 10,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 105,
      vendorModelId: "kling-3.0-edit",
      description: "Kling 3.0 video editing",
      category: "Premium"
    },
    {
      key: "kling-o1",
      label: "Kling O1",
      provider: "Kling",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 50, "1080p": 60 },
      durations: null,
      minDuration: 3,
      maxDuration: 10,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 106,
      vendorModelId: "kling-o1",
      description: "Kling O1 reasoning model",
      category: "Premium"
    },
    {
      key: "kling-3.0-motion",
      label: "Kling 3.0 Motion",
      provider: "Kling",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 50, "1080p": 80 },
      durations: null,
      minDuration: 3,
      maxDuration: 15,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 107,
      vendorModelId: "kling-3.0-motion",
      description: "Kling 3.0 motion enhancement",
      category: "Premium"
    },
    {
      key: "kling-2.6-motion",
      label: "Kling 2.6 Motion",
      provider: "Kling",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 30, "1080p": 45 },
      durations: [5, 10],
      minDuration: null,
      maxDuration: null,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 108,
      vendorModelId: "kling-2.6-motion",
      description: "Kling 2.6 motion enhancement",
      category: "Standard"
    },
    {
      key: "kling-lipsync",
      label: "Kling LipSync",
      provider: "Kling",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 30, "1080p": 30 },
      durations: [5, 10],
      minDuration: null,
      maxDuration: null,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 112,
      vendorModelId: "kling-lipsync",
      description: "Kling lip sync generation",
      category: "Specialty"
    },
    {
      key: "seedance-2-fast",
      label: "Seedance 2 Fast",
      provider: "Seedance",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "480p": 60, "720p": 95 },
      durations: null,
      minDuration: 4,
      maxDuration: 15,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 200,
      vendorModelId: "seedance-2-fast",
      description: "Seedance 2 fast generation",
      category: "Fast"
    },
    {
      key: "seedance-2-pro",
      label: "Seedance 2 Pro",
      provider: "Seedance",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "480p": 80, "720p": 135 },
      durations: null,
      minDuration: 4,
      maxDuration: 15,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 201,
      vendorModelId: "seedance-2-pro",
      description: "Seedance 2 pro quality",
      category: "Premium"
    },
    {
      key: "seedance-omni-fast",
      label: "Seedance Omni Fast",
      provider: "Seedance",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 95 },
      durations: null,
      minDuration: 4,
      maxDuration: 15,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 202,
      vendorModelId: "seedance-omni-fast",
      description: "Seedance Omni fast generation",
      category: "Fast"
    },
    {
      key: "seedance-omni-pro",
      label: "Seedance Omni Pro",
      provider: "Seedance",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 135 },
      durations: null,
      minDuration: 4,
      maxDuration: 15,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 203,
      vendorModelId: "seedance-omni-pro",
      description: "Seedance Omni pro quality",
      category: "Premium"
    },
    {
      key: "seedance-omni-fast-vip",
      label: "Seedance Omni Fast VIP",
      provider: "Seedance",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 135 },
      durations: null,
      minDuration: 4,
      maxDuration: 15,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 204,
      vendorModelId: "seedance-omni-fast-vip",
      description: "Seedance Omni fast VIP tier",
      category: "VIP"
    },
    {
      key: "seedance-omni-pro-vip",
      label: "Seedance Omni Pro VIP",
      provider: "Seedance",
      type: "video",
      billing: "per_second",
      credits: null,
      creditsPerSecond: { "720p": 175 },
      durations: null,
      minDuration: 4,
      maxDuration: 15,
      aspectRatios: ["16:9", "9:16"],
      imageModes: [],
      maxRefImages: 0,
      freeAccess: false,
      routed: false,
      enabled: false,
      sortOrder: 205,
      vendorModelId: "seedance-omni-pro-vip",
      description: "Seedance Omni pro VIP tier",
      category: "VIP"
    }
  ];

  for (const m of models) {
    const record = new Record(collection);
    record.set("key", m.key);
    record.set("label", m.label);
    record.set("provider", m.provider);
    record.set("type", m.type);
    record.set("billing", m.billing);
    if (m.credits) record.set("credits", m.credits);
    if (m.creditsPerSecond) record.set("creditsPerSecond", m.creditsPerSecond);
    if (m.durations) record.set("durations", m.durations);
    if (m.minDuration != null) record.set("minDuration", m.minDuration);
    if (m.maxDuration != null) record.set("maxDuration", m.maxDuration);
    if (m.aspectRatios) record.set("aspectRatios", m.aspectRatios);
    if (m.imageModes) record.set("imageModes", m.imageModes);
    record.set("maxRefImages", m.maxRefImages || 0);
    record.set("freeAccess", !!m.freeAccess);
    record.set("routed", !!m.routed);
    record.set("enabled", !!m.enabled);
    record.set("sortOrder", m.sortOrder || 0);
    record.set("vendorModelId", m.vendorModelId || m.key);
    record.set("description", m.description || "");
    record.set("category", m.category || "Standard");

    try {
      app.save(record);
    } catch (e) {
      if (e.message && e.message.includes("duplicate")) {
        console.log(`Model ${m.key} already exists, skipping`);
      } else {
        console.log(`Error saving model ${m.key}: ${e.message}`);
      }
    }
  }

  console.log(`Seeded ${models.length} models into model_catalog`);
}, (app) => {
  // Rollback: delete all seeded records
  try {
    const records = app.findAllRecords("model_catalog");
    for (const record of records) {
      app.delete(record);
    }
    console.log("Rolled back all model_catalog records");
  } catch (e) {
    console.log("Error rolling back model_catalog:", e.message);
  }
})
